### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by mohdbashir** [letyii/yii2-rbac-mongodb#3]
PHP Notice 'yii\base\ErrorException' with message 'unserialize(): Error at offset 0 of 122 bytes'
in F:\xampp\htdocs\redealnew\trunk\vendor\letyii\yii2-rbac-mongodb\MongodbManager.php:402

**Comment by nguago** [comment]
Fixed !

**Comment by mohdbashir** [comment]
You don't have any solution to fix this isssue?
