### ISSUE TITLE
Errors getPermissionsByUser

### ISSUE THREAD

**Issue by KasselR** [letyii/yii2-rbac-mongodb#5]
in getPermissionsByUser there are 2 errors:
$query = (new Query)->select('item_name')
            ->from($this->assignmentTable)
            ->where(['user_id' => (string)$userId]);
must be:
$query = (new Query)->select(['item_name'])
            ->from($this->assignmentTable)
            ->where(['user_id' => (string)$userId]);

and
$this->getChildrenRecursive($roleName['item_name'], $childrenList, $result);
must be:
$this->getChildrenRecursive($role['item_name'], $childrenList, $result);

please can you fix this.

regards

**Comment by nguago** [comment]
@maibaduy Em xem và xử lý vấn đề này nhé!

**Comment by maibaduy** [comment]
@KasselR Fixed, thanks for reporting
