### ISSUE TITLE
Class letyii\rbacmongodb\MongodbManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (yii\rbac\ManagerInterface::canAddChild)"

### ISSUE THREAD

**Issue by avtop3** [letyii/yii2-rbac-mongodb#6]
Exception when calling method 

<pre>\Yii::$app->user->can()</pre>

Class letyii\rbacmongodb\MongodbManager contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (yii\rbac\ManagerInterface::canAddChild)"
name
IDE gives error hint:

> Class must be declared abstract or implement method 'canAddChild'

Yii version is 2.0.8-dev

**Comment by nguago** [comment]
@maibaduy Em xử lý giúp anh vụ này nhé!

**Comment by maibaduy** [comment]
Fixed, thanks for reporting
